-- Create analytics table
create table if not exists public.analytics (
  id bigint generated by default as identity primary key,
  event_type text not null, -- 'page_view', 'click', 'share'
  path text,
  user_id uuid references auth.users,
  metadata jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.analytics enable row level security;

-- Policies
-- Anyone can insert analytics (anon or auth)
create policy "Anyone can insert analytics" on public.analytics
  for insert with check (true);

-- Only admins can view analytics
create policy "Admins can view analytics" on public.analytics
  for select using (
    exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' )
  );
