-- Community Platform Upgrade Schema

-- 1. Update Profiles Table
-- Add 'bio' column if it doesn't exist
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'bio') then
    alter table public.profiles add column bio text;
  end if;
end $$;

-- 2. Create Messages Table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  content text not null,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_read boolean default false
);

-- Enable RLS
alter table public.messages enable row level security;

-- Policies for Messages
drop policy if exists "Users can insert their own messages" on public.messages;
create policy "Users can insert their own messages" on public.messages
  for insert with check (auth.uid() = sender_id);

drop policy if exists "Users can view messages sent to or by them" on public.messages;
create policy "Users can view messages sent to or by them" on public.messages
  for select using (
    auth.uid() = sender_id or auth.uid() = receiver_id
  );

-- 3. Automatic Profile Creation Trigger
-- Ensure this function exists and handles metadata
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id, 
    new.email, 
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)), 
    coalesce(new.raw_user_meta_data->>'avatar_url', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Re-create trigger to ensure it's active
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 4. Storage for Avatars (Optional, if not already set)
-- Ensure 'avatars' bucket exists
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

-- Storage Policies for Avatars
drop policy if exists "Avatar images are publicly accessible" on storage.objects;
create policy "Avatar images are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'avatars' );

drop policy if exists "Anyone can upload an avatar" on storage.objects;
create policy "Authenticated users can upload avatars"
  on storage.objects for insert
  to authenticated
  with check ( bucket_id = 'avatars' and auth.uid() = owner );

drop policy if exists "Users can update their own avatar" on storage.objects;
create policy "Users can update their own avatar"
  on storage.objects for update
  to authenticated
  using ( bucket_id = 'avatars' and auth.uid() = owner );
