-- Create messages table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  content text not null,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_read boolean default false
);

-- Enable RLS
alter table public.messages enable row level security;

-- Policies
create policy "Users can insert their own messages" on public.messages
  for insert with check (auth.uid() = sender_id);

create policy "Users can view messages sent to or by them" on public.messages
  for select using (
    auth.uid() = sender_id or auth.uid() = receiver_id
  );

-- Function to handle new user signup (if not already exists from previous setup)
-- This ensures every auth user has a public profile
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger (safe to run multiple times if using 'create or replace')
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
