-- Create a table for public profiles (optional, if you want public author pages)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  role text default 'reader' check (role in ('admin', 'editor', 'reader')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

-- Create a table for categories
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for categories
alter table public.categories enable row level security;

-- Create articles table
create table public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  subtitle text,
  excerpt text,
  content text, -- HTML content from rich text editor
  image_url text,
  video_url text,
  image_caption text,
  category_id bigint references public.categories(id),
  author_id uuid references public.profiles(id),
  published_at timestamp with time zone,
  is_featured boolean default false,
  is_breaking boolean default false,
  status text default 'draft' check (status in ('draft', 'published', 'archived')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for articles
alter table public.articles enable row level security;

-- POLICIES --

-- Profiles:
-- Public can view profiles (for author info)
create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

-- Users can insert their own profile
create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

-- Articles:
-- Published articles are viewable by everyone
create policy "Published articles are viewable by everyone." on public.articles
  for select using (status = 'published');

-- Admins/Editors can view all articles
create policy "Admins can view all articles." on public.articles
  for select using (
    exists ( select 1 from public.profiles where id = auth.uid() and role in ('admin', 'editor') )
  );

-- Admins/Editors can insert/update articles
create policy "Admins can insert articles." on public.articles
  for insert with check (
    exists ( select 1 from public.profiles where id = auth.uid() and role in ('admin', 'editor') )
  );

create policy "Admins can update articles." on public.articles
  for update using (
    exists ( select 1 from public.profiles where id = auth.uid() and role in ('admin', 'editor') )
  );

-- Categories:
-- Readable by everyone
create policy "Categories are viewable by everyone" on public.categories
  for select using (true);
  
-- Only admins can manage categories
create policy "Admins can insert categories" on public.categories
  for insert with check (
    exists ( select 1 from public.profiles where id = auth.uid() and role in ('admin', 'editor') )
  );

-- STORAGE BUCKETS --
-- Note: You must create a storage bucket named 'images' in the Supabase Dashboard.
-- Policy: Give public read access, authenticated insert access.
